name: fx_calc
description: FX Calc – Calculator & Currency Converter

publish_to: 'none'

version: 1.0.4+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.0
  math_expressions: ^2.4.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
